### ISSUE TITLE
Path for pip incorrect

### ISSUE THREAD

**Issue by rlmoser** [puppetlabs/pltraining-learning#44]
When bootstrapping a new learning environment I received these messages:
==> learning: Error: Could not find command '/bin/pip'
==> learning: Error: /Stage[main]/Learning::Graphite_reqs/Exec[/bin/pip install requests[security]]/returns: change from notrun to 0 failed: Could not find command '/bin/pip'

The pip executable is installed to /usr/bin/pip and not /bin/pip.

**Comment by joshsamuelson** [comment]
This is fixed now.
